typography_spectrum: 0.98655869092322
content_rating:
  adult: false
color:
  brandStrength: 0.5847763226816596
  lightness: 0.9543273123078011
  saturation: 0.4295279744623395
  rhythmicContrast: 0.5949037976135121
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
github: true
layout_spectrum: 0.7445957011009318
analytics:
  twitter: '@graceartevents'
author:
  name: Sarah Greenwood
  email: info@graceartevents.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4aae15bd-117c-4915-8fe4-b32c1d8544a3.png
name: "\_"
navigation:
  - name: LIFE DRAWING SESSIONS
    id: 45ca1797-acc6-4c7c-8b92-5c52afedf236
    type: content
  - name: WHAT'S ON
    id: ba22dfe1-5eda-454c-8b34-7694b3b8d9eb
    type: content
  - name: LIFE MODEL TRAINING
    id: 48e8cc92-6cf6-464b-a3e9-0aeea8655190
    type: content
  - name: MAKE $$$ WITH YOUR PASSION
    id: b9fbe01b-0799-4113-b883-ddf543cfb1df
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/251ebac9-d0a3-4aa9-b36b-19dd728f90ce.jpg
title: Grace Art Events
content: []
description: Putting LIFE into DRAWING!
purpose:
  - type: external
    url: 'http://www.facebook.com/GraceArtEvent5'
    label: Like us on Facebook
  - type: external
    url: 'http://eepurl.com/bE-Fa1'
    label: Join Our Mailing List
